name: school_management_frog
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  dart_frog: ^0.3.0
  mysql1: ^0.20.0
  mysql_client: ^0.0.27

dev_dependencies:
  # build_runner: ^2.3.3
  # json_serializable: ^6.6.1
  #
  mocktail: ^0.3.0
  test: ^1.19.2
  # very_good_analysis: ^4.0.0
